<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class article_company extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("article_company")->insert(
            [
            ["id_fields_career" => "6",
            "id_level" => 1,
            "id_company" => 1,
            "id_city" => '01',
            "title" => "Tuyển lập trình viên PHP",
            "request" => "Yêu cầu thành thạo PHP cơ bản",
            "address_work" => "93/5 sông cầu",
            "status_address" => 1,
            "salary_from" => 5000000,
            "salary_to" => 7000000,
            "status_salary" => 1,
            "date_accept_profile" => date("Y-m-d"),
            "gender" => 1,
            "age_from" => 18,
            "age_to" => 22,
            "experience" => 2,
            "description_work" => "Làm dự án thực tạo website",
            "description_other" => "",
            "status" => 1],
            ["id_fields_career" => "6",
            "id_level" => 1,
            "id_company" => 2,
            "id_city" => '01',
            "title" => "Tuyển lập trình viên PHP",
            "request" => "Yêu cầu thành thạo PHP cơ bản",
            "address_work" => "93/5 sông cầu",
            "status_address" => 1,
            "salary_from" => 5000000,
            "salary_to" => 7000000,
            "status_salary" => 1,
            "date_accept_profile" => date("Y-m-d"),
            "gender" => 1,
            "age_from" => 18,
            "age_to" => 22,
            "experience" => 2,
            "description_work" => "Làm dự án thực tạo website",
            "description_other" => "",
            "status" => 1],
            ["id_fields_career" => "6",
            "id_level" => 1,
            "id_company" => 3,
            "id_city" => '01',
            "title" => "Tuyển lập trình viên PHP",
            "request" => "Yêu cầu thành thạo PHP cơ bản",
            "address_work" => "93/5 sông cầu",
            "status_address" => 1,
            "salary_from" => 5000000,
            "salary_to" => 7000000,
            "status_salary" => 1,
            "date_accept_profile" => date("Y-m-d"),
            "gender" => 1,
            "age_from" => 18,
            "age_to" => 22,
            "experience" => 2,
            "description_work" => "Làm dự án thực tạo website",
            "description_other" => "",
            "status" => 1],
            ["id_fields_career" => "6",
            "id_level" => 1,
            "id_company" => 1,
            "id_city" => '01',
            "title" => "Tuyển lập trình viên PHP",
            "request" => "Yêu cầu thành thạo PHP cơ bản",
            "address_work" => "93/5 sông cầu",
            "status_address" => 1,
            "salary_from" => 5000000,
            "salary_to" => 7000000,
            "status_salary" => 1,
            "date_accept_profile" => date("Y-m-d"),
            "gender" => 1,
            "age_from" => 18,
            "age_to" => 22,
            "experien`ce" => 2,
            "description_work" => "Làm dự án thực tạo website",
            "description_other" => "",
            "status" => 1],
            ["id_fields_career" => "6",
            "id_level" => 1,
            "id_company" => 3,
            "id_city" => '01',
            "title" => "Tuyển lập trình viên PHP",
            "request" => "Yêu cầu thành thạo PHP cơ bản",
            "address_work" => "93/5 sông cầu",
            "status_address" => 1,
            "salary_from" => 5000000,
            "salary_to" => 7000000,
            "status_salary" => 1,
            "date_accept_profile" => date("Y-m-d"),
            "gender" => 1,
            "age_from" => 18,
            "age_to" => 22,
            "experience" => 2,
            "description_work" => "Làm dự án thực tạo website",
            "description_other" => "",
            "status" => 1],
            ["id_fields_career" => "6",
            "id_level" => 1,
            "id_company" => 2,
            "id_city" => '01',
            "title" => "Tuyển lập trình viên PHP",
            "request" => "Yêu cầu thành thạo PHP cơ bản",
            "address_work" => "93/5 sông cầu",
            "status_address" => 1,
            "salary_from" => 5000000,
            "salary_to" => 7000000,
            "status_salary" => 1,
            "date_accept_profile" => date("Y-m-d"),
            "gender" => 1,
            "age_from" => 18,
            "age_to" => 22,
            "experience" => 2,
            "description_work" => "Làm dự án thực tạo website",
            "description_other" => "",
            "status" => 1],
        ]);
    }
}